import { StyleSheet } from 'react-native';

export const ticketStyles = StyleSheet.create({
  modalBackground: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.65)',
  },
  ticketContainer: {
    width: '100%',
    maxWidth: 800,
    backgroundColor: '#fff',
    borderRadius: 12,
    paddingVertical: 24,
    paddingHorizontal: 20,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 6,
    elevation: 8,
  },
  barberName: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#111',
    textAlign: 'center',
  },
  slogan: {
    fontSize: 12,
    fontStyle: 'italic',
    color: '#666',
    marginTop: 2,
    marginBottom: 10,
    textAlign: 'center',
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 1,
    color: '#333',
    marginBottom: 12,
  },
  ticketLine: {
    borderBottomWidth: 1,
    borderBottomColor: '#ddd',
    width: '100%',
    marginVertical: 10,
  },
  detailRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    marginBottom: 8,
  },
  detailLabel: {
    fontSize: 15,
    fontWeight: '600',
    color: '#444',
  },
  detailValue: {
    fontSize: 15,
    color: '#222',
    textAlign: 'right',
    flexShrink: 1,
  },
  thankYouText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#007AFF',
    marginTop: 18,
    marginBottom: 10,
  },
  printButton: {
    backgroundColor: '#198754',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 8,
    marginTop: 12,
    width: '100%',
    alignItems: 'center',
  },
  printButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  closeButton: {
    backgroundColor: '#6c757d',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 8,
    marginTop: 10,
    width: '100%',
    alignItems: 'center',
  },
  closeButtonText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '600',
  },
  buttonContainer: {
  marginTop: 20,
  alignItems: 'center',
},

});
